name: Bundle

on:
  pull_request:
    branches:
      - master

jobs:
  bundle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Bundle Directory
        run: 

